cmd_/memverge/home/catrin/modified_fuse/tools/objtool/help.o := gcc -Wp,-MD,/memverge/home/catrin/modified_fuse/tools/objtool/.help.o.d -Wp,-MT,/memverge/home/catrin/modified_fuse/tools/objtool/help.o -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -fno-strict-aliasing -ggdb3 -Wall -Wextra -std=gnu99 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -O6 -Werror -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/memverge/home/catrin/modified_fuse/tools/include/ -I/memverge/home/catrin/modified_fuse/include/uapi -I/memverge/home/catrin/modified_fuse/include -D"BUILD_STR(s)=\#s" -c -o /memverge/home/catrin/modified_fuse/tools/objtool/help.o help.c

source_/memverge/home/catrin/modified_fuse/tools/objtool/help.o := help.c

deps_/memverge/home/catrin/modified_fuse/tools/objtool/help.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/include/bits/stdio2.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/xlocale.h \
  /usr/include/sys/types.h \
  /usr/include/time.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/bits/select2.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/bits/stdlib.h \
  /usr/include/string.h \
  /usr/include/bits/string.h \
  /usr/include/bits/string2.h \
  /usr/include/bits/string3.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/string.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdbool.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/asm/types.h \
  /memverge/home/catrin/modified_fuse/include/uapi/asm-generic/types.h \
  /memverge/home/catrin/modified_fuse/include/uapi/asm-generic/int-ll64.h \
  /usr/include/asm/bitsperlong.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitsperlong.h \
  /memverge/home/catrin/modified_fuse/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /memverge/home/catrin/modified_fuse/include/uapi/asm-generic/posix_types.h \
  /usr/include/termios.h \
  /usr/include/bits/termios.h \
  /usr/include/sys/ttydefaults.h \
  /usr/include/sys/ioctl.h \
  /usr/include/bits/ioctls.h \
  /usr/include/asm/ioctls.h \
  /memverge/home/catrin/modified_fuse/include/uapi/asm-generic/ioctls.h \
  /memverge/home/catrin/modified_fuse/include/uapi/linux/ioctl.h \
  /usr/include/asm/ioctl.h \
  /memverge/home/catrin/modified_fuse/include/uapi/asm-generic/ioctl.h \
  /usr/include/bits/ioctl-types.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/bits/unistd.h \
  /usr/include/dirent.h \
  /usr/include/bits/dirent.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /memverge/home/catrin/modified_fuse/include/uapi/linux/limits.h \
  subcmd-util.h \
  help.h \
  exec-cmd.h \

/memverge/home/catrin/modified_fuse/tools/objtool/help.o: $(deps_/memverge/home/catrin/modified_fuse/tools/objtool/help.o)

$(deps_/memverge/home/catrin/modified_fuse/tools/objtool/help.o):
