cmd_/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o := gcc -Wp,-MD,/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/.decode.o.d -Wp,-MT,/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o -Wall -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -fno-strict-aliasing -fomit-frame-pointer -O2 -g -I/memverge/home/catrin/modified_fuse/tools/include -I/memverge/home/catrin/modified_fuse/tools/lib -D"BUILD_STR(s)=\#s" -I/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/insn -c -o /memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o arch/x86/decode.c

source_/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o := arch/x86/decode.c

deps_/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/types.h \
  /usr/include/time.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  arch/x86/insn/insn.h \
  arch/x86/insn/inat.h \
  arch/x86/insn/inat_types.h \
  arch/x86/insn/inat.c \
  arch/x86/insn/insn.h \
  arch/x86/insn/inat-tables.c \
  arch/x86/insn/insn.c \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/bits/string.h \
  /usr/include/bits/string2.h \
  arch/x86/../../elf.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/elf.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/list.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdbool.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /usr/include/asm/bitsperlong.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitsperlong.h \
  /memverge/home/catrin/modified_fuse/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/poison.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/compiler.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/compiler-gcc.h \
  /usr/include/byteswap.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/hashtable.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/bitops.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/__ffs.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/__ffz.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/fls.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/__fls.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/fls64.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/find.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/hweight.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/arch_hweight.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/const_hweight.h \
  /memverge/home/catrin/modified_fuse/tools/include/asm-generic/bitops/atomic.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/hash.h \
  /memverge/home/catrin/modified_fuse/tools/include/linux/log2.h \
  arch/x86/../../arch.h \
  arch/x86/../../elf.h \
  arch/x86/../../warn.h \

/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o: $(deps_/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o)

$(deps_/memverge/home/catrin/modified_fuse/tools/objtool/arch/x86/decode.o):
